export enum SecurityStatus {
  MONITORING = 'MONITORING',
  PERSON_DETECTED = 'PERSON_DETECTED',
  UNKNOWN_PERSON = 'UNKNOWN_PERSON',
  SUSPICIOUS_EVENT = 'SUSPICIOUS_EVENT',
  VALIDATING = 'VALIDATING',
  EMERGENCY = 'EMERGENCY'
}
